#!/usr/bin/env python3
"""Build js/quizzes-wN.js from every data/quizzes-wN.json.

- Shuffles each question's choices with a seeded RNG (seed = quiz id + question
  number) so the correct answer's position is random but reproducible, and the
  web quiz and printed quiz always agree.
- Re-rolls the seed for a quiz until the correct-answer positions are balanced
  (no letter used for more than 3 of 8 questions, every letter used at least once).
- Lints for the "guess from appearance" problems: a correct answer that is much
  longer than the distractors, or a distractor that is much shorter than the rest.

Each week is independent: lecture pages load only their own week's file.
Run from anywhere:  /usr/bin/python3 tools/build_quizzes.py
"""
import json
import random
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
JS = ROOT / "js"


def shuffle_quiz(qid, quiz):
    n = len(quiz["questions"])
    max_share = max(2, -(-n * 3 // 8))  # 3 of 8; scales for longer quizzes
    for attempt in range(1000):
        rng = random.Random(f"{qid}#{attempt}")
        shuffled = []
        for q in quiz["questions"]:
            order = list(range(len(q["choices"])))
            rng.shuffle(order)
            new_q = dict(q)
            new_q["choices"] = [q["choices"][i] for i in order]
            new_q["answer"] = order.index(q["answer"])
            shuffled.append(new_q)
        positions = Counter(q["answer"] for q in shuffled)
        n_choices = len(quiz["questions"][0]["choices"])
        balanced = (max(positions.values()) <= max_share
                    and len(positions) == min(n_choices, n))
        if balanced:
            return shuffled, positions
    raise RuntimeError(f"could not balance {qid}")


def lint(qid, questions):
    warnings = []
    for i, q in enumerate(questions, 1):
        lens = [len(c) for c in q["choices"]]
        correct = lens[q["answer"]]
        others = [l for j, l in enumerate(lens) if j != q["answer"]]
        avg_other = sum(others) / len(others)
        if correct > 1.3 * avg_other and correct - avg_other > 12:
            warnings.append(f"{qid} Q{i}: correct answer is {correct} chars vs distractor avg {avg_other:.0f} — too long")
        if min(others) < 0.5 * correct and correct - min(others) > 12:
            warnings.append(f"{qid} Q{i}: a distractor ({min(others)} chars) is much shorter than the correct answer ({correct})")
        if len(set(q["choices"])) != len(q["choices"]):
            warnings.append(f"{qid} Q{i}: duplicate choices")
        if len(q["choices"]) != 4:
            warnings.append(f"{qid} Q{i}: {len(q['choices'])} choices (expected 4)")
    return warnings


def build_week(src):
    week = re.search(r"quizzes-w(\d+)\.json$", src.name).group(1)
    data = json.loads(src.read_text(encoding="utf-8"))
    out = {}
    warnings = []
    for qid, quiz in data.items():
        if not qid.endswith(f"-w{week}"):
            warnings.append(f"{qid}: id does not end in -w{week} (file {src.name})")
        questions, positions = shuffle_quiz(qid, quiz)
        warnings += lint(qid, questions)
        out[qid] = dict(quiz, questions=questions)
        letters = "".join("ABCD"[q["answer"]] for q in questions)
        print(f"{qid:14s} answers: {letters}   distribution: {dict(sorted(positions.items()))}")

    shuffled = DATA / f"quizzes-w{week}.shuffled.json"
    shuffled.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    js = (f"/* GENERATED by tools/build_quizzes.py from data/quizzes-w{week}.json — do not edit by hand. */\n"
          "window.QUIZZES = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
    outfile = JS / f"quizzes-w{week}.js"
    outfile.write_text(js, encoding="utf-8")
    print(f"wrote {outfile.relative_to(ROOT)} and {shuffled.relative_to(ROOT)}")
    return warnings


def main():
    sources = sorted(DATA.glob("quizzes-w*.json"), key=lambda p: int(re.search(r"w(\d+)", p.name).group(1)))
    sources = [s for s in sources if ".shuffled" not in s.name]
    if not sources:
        sys.exit("no data/quizzes-w*.json found")
    all_warnings = []
    for src in sources:
        all_warnings += build_week(src)
    if all_warnings:
        print("\nLINT WARNINGS:")
        for w in all_warnings:
            print("  -", w)
        sys.exit(1)
    print("lint: clean")


if __name__ == "__main__":
    main()
