/* NICUniversity vocabulary. Any of these words appearing in lesson text becomes tappable.
   say: how to pronounce it (also used by read-aloud). def: plain-language definition. */
window.VOCAB = {
  // --- university words ---
  "lecture":        { say: "LEK-chur", def: "A class where the professor teaches and you listen, think, and take notes." },
  "recitation":     { say: "reh-sih-TAY-shun", def: "A smaller session for practicing what the lecture taught — at NICUniversity, it's where you do your homework." },
  "professor":      { say: "pruh-FESS-er", def: "A teacher at a university. Most professors also do research — they discover new things, not just teach old ones." },
  "syllabus":       { say: "SILL-uh-bus", def: "The plan for a course: what you'll learn each week and how you'll be graded." },
  "transcript":     { say: "TRAN-script", def: "The official record of the courses you've taken and how you did." },
  "seminar":        { say: "SEM-ih-nar", def: "A small class built around discussion instead of a lecture." },
  "undergraduate":  { say: "un-der-GRAD-yoo-it", def: "A university student earning a first degree — usually four years. Doctors go to medical school after that." },
  "pre-med":        { say: "pree-MED", def: "Short for 'pre-medical' — the courses you take in university to prepare for medical school." },
  "neonatologist":  { say: "nee-oh-nay-TOL-uh-jist", def: "A doctor who specializes in newborn babies, especially sick and premature ones." },
  "premature":      { say: "pree-muh-CHOOR", def: "Born early — before 37 weeks of pregnancy. A premature baby is a 'preemie'." },

  // --- chemistry ---
  "atom":           { say: "AT-um", def: "The tiniest building block of ordinary matter. Everything you can touch is made of atoms — and they're so small that a single drop of water holds more of them than there are stars in the galaxy." },
  "atoms":          { say: "AT-umz", def: "The tiniest building blocks of ordinary matter. Everything you can touch is made of atoms." },
  "molecule":       { say: "MOL-uh-kyool", def: "Two or more atoms joined together. Water, oxygen gas, and sugar are all molecules." },
  "molecules":      { say: "MOL-uh-kyoolz", def: "Groups of atoms joined together. Water, oxygen gas, and sugar are all molecules." },
  "element":        { say: "EL-uh-ment", def: "One kind of atom. Oxygen, carbon, hydrogen, and gold are elements. There are about 118 of them, and only a few dozen matter for living things." },
  "elements":       { say: "EL-uh-ments", def: "The different kinds of atoms. Oxygen, carbon, hydrogen, and gold are elements." },
  "chemical formula": { say: "KEM-ih-kul FOR-myoo-luh", def: "The short recipe for a molecule, like H₂O — it lists which atoms and how many of each." },
  "subscript":      { say: "SUB-script", def: "A small number written low and to the right, like the 2 in H₂O. It tells you how many of that atom are in the molecule." },
  "oxygen":         { say: "OK-sih-jin", def: "The gas your cells need to burn fuel for energy. About one-fifth of the air is oxygen." },
  "carbon dioxide": { say: "KAR-bun dy-OK-side", def: "The waste gas your cells make when they burn fuel — CO₂. You breathe it out; plants breathe it in." },
  "nitrogen":       { say: "NY-truh-jin", def: "The gas that makes up most of the air (about 78%). You breathe it in and right back out — your body mostly ignores it." },
  "gas exchange":   { say: "gas eks-CHAYNJ", def: "The swap in the lungs: oxygen moves from air into blood, and carbon dioxide moves from blood into air." },
  "alveoli":        { say: "al-VEE-oh-lye", def: "The hundreds of millions of microscopic air balloons in the lungs where gas exchange happens." },
  "hemoglobin":     { say: "HEE-muh-glow-bin", def: "The protein inside red blood cells that grabs oxygen and carries it around the body. It's what makes blood red." },
  "surfactant":     { say: "sur-FAK-tunt", def: "The soap-like liquid that coats the lungs' air balloons so they don't stick shut. Preemies don't make enough of it yet." },
  "acid":           { say: "ASS-id", def: "A chemical that tastes sour and can be corrosive — lemon juice and stomach juice are acids. Blood is supposed to be only very slightly on the opposite (base) side." },
  "chemist":        { say: "KEM-ist", def: "A scientist who studies what things are made of and how they change." },
  "chemistry":      { say: "KEM-iss-tree", def: "The science of what things are made of and how they change into other things." },
  "experiment":     { say: "ek-SPEHR-ih-ment", def: "A careful test to find out if an idea is true. Scientists change one thing and watch what happens." },
  "percent":        { say: "per-SENT", def: "Out of one hundred. 21 percent means 21 out of every 100." },

  // --- biology ---
  "cell":           { say: "sell", def: "The smallest living unit of a body — a tiny bag of chemistry with its own instruction book. You are made of trillions of them." },
  "cells":          { say: "sells", def: "The smallest living units of a body. You are made of trillions of them, and you started as exactly one." },
  "nucleus":        { say: "NOO-klee-us", def: "The control center of a cell, where the DNA instruction book is kept." },
  "membrane":       { say: "MEM-brayn", def: "The thin skin around a cell that decides what comes in and what goes out." },
  "mitochondria":   { say: "my-toh-KON-dree-uh", def: "The power plants of the cell. They burn sugar with oxygen to make energy — that's where the oxygen you breathe finally gets used." },
  "cytoplasm":      { say: "SY-toh-plaz-um", def: "The jelly-like liquid that fills a cell and holds its parts." },
  "tissue":         { say: "TISH-oo", def: "A group of similar cells working together — muscle tissue, skin tissue, nerve tissue." },
  "tissues":        { say: "TISH-ooz", def: "Groups of similar cells working together — muscle, skin, nerve, and so on." },
  "organ":          { say: "OR-gun", def: "A body part made of several tissues doing one job — the heart, lungs, brain, and skin are all organs." },
  "organs":         { say: "OR-gunz", def: "Body parts made of several tissues doing one big job — the heart, lungs, brain, and skin." },
  "microscope":     { say: "MY-kruh-skope", def: "A tool with lenses that makes tiny things look big enough to see." },
  "microscopic":    { say: "my-kruh-SKOP-ik", def: "Too small to see without a microscope." },
  "cell division":  { say: "sell dih-VIZH-un", def: "When one cell splits into two. It's how bodies grow and heal — and how one cell becomes a whole baby." },
  "bacteria":       { say: "bak-TEER-ee-uh", def: "Tiny one-celled living things. Most are harmless or helpful; some cause infections." },
  "red blood cell": { say: "red blud sell", def: "The disc-shaped cell that carries oxygen using hemoglobin. Unusual: it has no nucleus, leaving more room for cargo." },
  "biologist":      { say: "by-OL-uh-jist", def: "A scientist who studies living things." },
  "biology":        { say: "by-OL-uh-jee", def: "The science of living things — how they're built, how they work, how they grow." },
  "trillion":       { say: "TRILL-yun", def: "A thousand billion — 1,000,000,000,000. Your body has around 30 trillion cells." },
  "organism":       { say: "OR-guh-niz-um", def: "Any single living thing — a bacterium, a tree, a baby, you." },
  "bilirubin":      { say: "bill-ee-ROO-bin", def: "The yellow leftover from recycling worn-out red blood cells. Too much of it causes jaundice." },

  // --- physics ---
  "pressure":       { say: "PRESH-er", def: "A push spread over an area. The same push on a smaller area makes a bigger pressure." },
  "area":           { say: "AIR-ee-uh", def: "How much surface something covers — the size of the flat space a push lands on." },
  "atmosphere":     { say: "AT-muss-feer", def: "The blanket of air around the Earth. Its weight presses on everything — about 760 mmHg at sea level." },
  "barometer":      { say: "buh-ROM-eh-ter", def: "An instrument that measures air pressure. Torricelli's mercury tube was the first one." },
  "mercury":        { say: "MER-kyoo-ree", def: "A silvery metal that is liquid at room temperature and about 13.6 times heavier than water. Old blood pressure meters used a column of it." },
  "mmHg":           { say: "millimeters of mercury", def: "A unit of pressure: how many millimeters high the push could lift a column of mercury. Used for blood pressure." },
  "cmH₂O":          { say: "centimeters of water", def: "A unit of gentle pressure: how many centimeters high the push could lift a column of water. Used for CPAP and ventilators." },
  "physicist":      { say: "FIZZ-ih-sist", def: "A scientist who studies forces, energy, motion, light, sound, and heat — the rules everything follows." },
  "physics":        { say: "FIZZ-iks", def: "The science of forces, energy, and motion — the rules that everything, living or not, has to follow." },
  "air leak":       { say: "air leek", def: "When an over-stretched air sac in the lung pops and air escapes into the chest, squashing the lung. A known danger of too much pressure." },
  "ventilator":     { say: "VEN-tih-lay-ter", def: "The machine that breathes for a baby through a tube in the windpipe, with every puff's size and pressure set precisely." },

  // --- calculus ---
  "calculus":       { say: "KAL-kyoo-lus", def: "The mathematics of change: how fast something is changing, and how much it adds up to over time." },
  "rate":           { say: "rayt", def: "How much something changes in each unit of time — like grams per day or miles per hour." },
  "rate of change": { say: "rayt of chaynj", def: "How much something changes per unit of time. Change ÷ time." },
  "slope":          { say: "slohp", def: "How steep a line on a graph is. On a weight graph, the slope IS the rate of growth." },
  "graph":          { say: "graf", def: "A picture of numbers. A line graph shows how something changes over time." },
  "average":        { say: "AV-er-ij", def: "The typical amount, found by adding everything up and dividing by how many there are." },
  "negative":       { say: "NEG-uh-tiv", def: "Less than zero. A negative rate of change means something is going down — like a newborn's weight in the first days." },
  "velocity":       { say: "veh-LOSS-ih-tee", def: "Speed with a direction. Doctors call the rate of growth on a growth chart 'growth velocity'." },
  "derivative":     { say: "deh-RIV-uh-tiv", def: "The calculus word for the rate of change at one exact moment — the steepness of the curve right there." },
  "kilogram":       { say: "KILL-oh-gram", def: "1,000 grams — about the weight of a liter of water. A 1 kg baby is a very small preemie." },
  "trend":          { say: "trend", def: "The overall direction of many measurements over time — up, down, or flat — as opposed to one single reading." },

  // --- statistics ---
  "statistics":     { say: "stuh-TISS-tiks", def: "The science of making sense of many numbers — what's typical, what's unusual, and how sure we can be." },
  "the mean":       { say: "the meen", def: "The average: add all the numbers, then divide by how many there are." },
  "the range":      { say: "the raynj", def: "The biggest number minus the smallest — how spread out the numbers are." },
  "data":          { say: "DAY-tuh", def: "Measurements and facts collected to learn something. One heart rate is a number; a hundred of them is data." },
  "Apgar score":    { say: "AP-gar score", def: "A 0-to-10 score of how a newborn is doing at 1 and 5 minutes after birth: heart rate, breathing, muscle tone, reflexes, and color, each scored 0, 1, or 2." },
  "anesthesiologist": { say: "an-ess-thee-zee-OL-uh-jist", def: "A doctor who keeps patients safely asleep and pain-free during operations — and watches their breathing and heart the whole time." },
  "normal range":   { say: "NOR-mul raynj", def: "The zone where most healthy people's measurements fall, found by measuring thousands of them." },

  // --- genetics ---
  "genetics":       { say: "jeh-NET-iks", def: "The science of the instruction book inside cells — DNA, genes, and how traits pass from parents to children." },
  "DNA":            { say: "D N A", def: "The long molecule that stores the body's instructions, written in four chemical letters: A, T, C, G." },
  "gene":           { say: "jeen", def: "One recipe in the DNA instruction book — the instructions for building one protein." },
  "genes":          { say: "jeenz", def: "The recipes in the DNA instruction book. Humans have about 20,000." },
  "chromosome":     { say: "KROH-muh-sohm", def: "One volume of the instruction book — a long, tightly wound piece of DNA. Human body cells have 46, in 23 pairs." },
  "chromosomes":    { say: "KROH-muh-sohmz", def: "The volumes of the instruction book. Human body cells have 46, in 23 pairs — one of each pair from each parent." },
  "protein":        { say: "PROH-teen", def: "A working molecule built from a gene's recipe. Hemoglobin, surfactant, and muscle are all made of proteins." },
  "proteins":       { say: "PROH-teenz", def: "The working molecules of the body, each built from a gene's recipe." },
  "identical twins":{ say: "eye-DEN-tih-kul twinz", def: "Twins from one fertilized egg that split in two — they share the same DNA." },
  "fraternal twins":{ say: "fruh-TER-nul twinz", def: "Twins from two separate eggs — ordinary siblings who happened to share a womb." },
  "mutation":       { say: "myoo-TAY-shun", def: "A typo in the DNA code. Most are harmless; a few cause diseases like sickle cell." },
  "double helix":   { say: "DUB-ul HEE-liks", def: "The twisted-ladder shape of the DNA molecule." },
  "inherit":        { say: "in-HAIR-it", def: "To receive from your parents — features passed down through DNA." },

  // --- psychology ---
  "psychology":     { say: "sy-KOL-uh-jee", def: "The science of the mind and behavior — what people (and babies) think, feel, and do." },
  "psychologist":   { say: "sy-KOL-uh-jist", def: "A scientist who studies minds and behavior." },
  "behavior":       { say: "bee-HAY-vyer", def: "What someone does — looking, sucking, turning, crying, smiling. Babies can't talk, so behavior is how they tell us things." },
  "neurons":        { say: "NOOR-onz", def: "Brain cells that send signals to each other. You have about 86 billion, wiring up at over a million connections a second in early life." },
  "neuron":         { say: "NOOR-on", def: "A brain cell that sends signals. A newborn's neurons are connecting at more than a million connections per second." },
  "developmental care": { say: "dih-vel-up-MEN-tul care", def: "Running a NICU around the baby's needs — dim lights, less noise, protected sleep, gentle handling, parents close." },
  "stress":         { say: "stress", def: "The body's alarm state: faster heart, stress hormones, tense muscles. Babies have it too — and it can be measured." },
  "womb":           { say: "woom", def: "The uterus — the place inside the mother where a baby grows before birth." },
  "third trimester": { say: "third try-MESS-ter", def: "The last three months of pregnancy (about weeks 27–40), when the brain and lungs do most of their finishing work." },

  // --- sociology ---
  "sociology":      { say: "so-see-OL-uh-jee", def: "The science of people in groups — how they organize, the roles they take, and the rules they follow." },
  "sociologist":    { say: "so-see-OL-uh-jist", def: "A scientist who studies groups, organizations, and societies." },
  "society":        { say: "suh-SY-eh-tee", def: "A large group of people living and working together with shared rules and roles. A hospital is a small society." },
  "role":           { say: "rohl", def: "The job and expected behavior a person has in a group — nurse, parent, student, captain." },
  "hierarchy":      { say: "HY-er-ar-kee", def: "A ranking of who is in charge of whom. Useful for decisions; dangerous when it stops people from speaking up." },
  "regionalization": { say: "ree-jun-ul-ih-ZAY-shun", def: "Organizing hospitals so the sickest babies are born in, or moved to, the ones equipped to care for them." },
  "respiratory therapist": { say: "RESS-pir-uh-tor-ee THAIR-uh-pist", def: "The breathing-machine expert on the team — runs ventilators and CPAP and helps at every fragile delivery." },
  "pharmacist":     { say: "FAR-muh-sist", def: "The medicine expert — prepares TPN recipes and checks every dose for tiny bodies." },
  "social worker":  { say: "SO-shul WER-ker", def: "The team member who supports families — stress, money, housing, paperwork, and getting through the hardest days." },
  "lactation consultant": { say: "lak-TAY-shun kun-SUL-tunt", def: "An expert who helps mothers pump and provide breast milk for their babies." },
  "infection control": { say: "in-FEK-shun kun-TROHL", def: "Everything done to keep germs away from patients — handwashing, cleaning, gloves, gowns." },

  // --- shared NICU words (flashbacks) ---
  "isolette":       { say: "EYE-so-let", def: "The clear, warm, humid incubator bed that keeps a preemie at the right temperature." },
  "pulse oximeter": { say: "pulse ok-SIM-eh-ter", def: "The glowing foot band that measures oxygen in the blood using red and infrared light." },
  "CPAP":           { say: "SEE-pap", def: "Continuous Positive Airway Pressure — a gentle air cushion through nose prongs that keeps a preemie's lungs partly inflated." },
  "jaundice":       { say: "JAWN-diss", def: "Yellow-tinted skin from bilirubin building up. Very common in newborns; treated with blue light." },
  "kangaroo care":  { say: "kang-guh-ROO care", def: "Holding a baby skin-to-skin on a parent's chest. It keeps the baby warm and steadies heart rate and breathing." },

  // ===================== Week 2 =====================
  // --- seminar ---
  "big idea":       { say: "big eye-DEE-uh", def: "A load-bearing sentence in a lecture. Forget it and the rest stops making sense." },
  "detail":         { say: "DEE-tale", def: "A support for an idea: a number, a date, an example, a story. You can rebuild it from the idea." },
  "details":        { say: "DEE-tales", def: "The supports for an idea: numbers, dates, examples, stories." },
  "retrieval practice": { say: "rih-TREE-vul PRAK-tiss", def: "Pulling an idea out of your own head — saying it, writing it, teaching it — instead of rereading it. It works better." },
  "mirror writing": { say: "MEER-er RY-ting", def: "Writing backwards, right to left, so it reads normally in a mirror. Leonardo da Vinci's habit." },
  "anatomy":        { say: "uh-NAT-uh-mee", def: "The study of how the body is built — what's where, and what it's connected to." },
  "notebook":       { say: "NOTE-book", def: "Where a scientist thinks on paper: drawings, questions, and ideas. Leonardo filled thousands of pages." },

  // --- chemistry ---
  "base":           { say: "bayss", def: "A chemical that grabs loose hydrogen. Bases feel slippery and taste bitter — soap and baking soda are bases. pH above 7." },
  "bases":          { say: "BAY-sez", def: "Chemicals that grab loose hydrogen — soap, baking soda, bleach. The opposite of acids." },
  "acids":          { say: "ASS-idz", def: "Chemicals that let go of loose hydrogen. Sour — lemon juice, vinegar, stomach acid. pH below 7." },
  "pH":             { say: "P H", def: "The 0-to-14 ruler for acid. 7 is neutral; lower is more acid; higher is more base. Each step is ten times." },
  "neutral":        { say: "NOO-trul", def: "Neither acid nor base — pH 7, like pure water." },
  "neutralize":     { say: "NOO-truh-lize", def: "What an acid and a base do to each other: cancel out. Baking soda and vinegar fizzing is neutralizing." },
  "carbonic acid":  { say: "kar-BON-ik ASS-id", def: "What carbon dioxide becomes when it dissolves in water — H₂CO₃. The body's main acid, and the sharp taste of soda water." },
  "bicarbonate":    { say: "by-KAR-buh-nit", def: "Blood's acid sponge: a base that catches loose hydrogen before it does damage. Baking soda is sodium bicarbonate." },
  "blood gas":      { say: "blud gas", def: "A few-drops-of-blood test that reports pH, carbon dioxide, oxygen, and bicarbonate. Read like clues." },
  "acidosis":       { say: "ass-ih-DOH-sis", def: "Blood with too much acid — pH below 7.35. From the lungs (CO₂ piling up) or from the cells (starving for oxygen)." },
  "lactic acid":    { say: "LAK-tik ASS-id", def: "The acid cells make when they burn sugar without enough oxygen. The burn in your legs after a sprint." },
  "indicator":      { say: "IN-dih-kay-ter", def: "A dye that changes color with pH. Red-cabbage juice is one; litmus is the oldest." },
  "kidneys":        { say: "KID-neez", def: "The two bean-shaped organs that filter blood, make urine, and slowly adjust the blood's bicarbonate." },

  // --- biology ---
  "atrium":         { say: "AY-tree-um", def: "An upstairs room of the heart, where blood arrives. There are two — one for each side." },
  "atria":          { say: "AY-tree-uh", def: "The two upstairs receiving rooms of the heart." },
  "ventricle":      { say: "VEN-trih-kul", def: "A downstairs pumping room of the heart, with thick muscular walls. The left one pushes blood to the whole body." },
  "ventricles":     { say: "VEN-trih-kulz", def: "The two downstairs pumping rooms of the heart." },
  "valve":          { say: "valv", def: "A one-way door in the heart or a vein. 'Lub-dub' is valves closing." },
  "valves":         { say: "valvz", def: "One-way doors in the heart and veins that stop blood sloshing backward." },
  "artery":         { say: "AR-tuh-ree", def: "A thick, stretchy pipe carrying blood away from the heart, under pressure." },
  "arteries":       { say: "AR-tuh-reez", def: "The pipes carrying blood away from the heart — the blood-pressure pipes." },
  "vein":           { say: "vayn", def: "A thinner, floppier pipe carrying blood back to the heart, at low pressure." },
  "veins":          { say: "vaynz", def: "The pipes carrying blood back to the heart. They have one-way valves inside." },
  "plasma":         { say: "PLAZ-muh", def: "The watery part of blood — about 55% — that carries salt, sugar, proteins, and bicarbonate." },
  "platelets":      { say: "PLAYT-lits", def: "Tiny cell fragments in the blood that plug leaks — the start of a scab." },
  "white blood cells": { say: "wite blud sells", def: "The blood's defenders. They hunt bacteria and other germs." },
  "circulation":    { say: "sir-kyoo-LAY-shun", def: "Blood going around the loop: heart → lungs → heart → body → heart. Proved by William Harvey in 1628." },
  "ductus arteriosus": { say: "DUK-tus ar-teer-ee-OH-sus", def: "The fetal bypass pipe that lets blood skip the unused lungs before birth. It should close within days of birth." },
  "PDA":            { say: "P D A", def: "Patent ductus arteriosus — the bypass pipe stayed open after birth. Common in preemies; it floods the lungs and shortchanges the body." },
  "placenta":       { say: "pluh-SEN-tuh", def: "The organ in the womb that passes oxygen and food from mother to baby through the umbilical cord." },
  "umbilical cord": { say: "um-BILL-ih-kul kord", def: "The baby's lifeline before birth: two arteries out and one vein in. Its stump is where umbilical catheters go." },
  "transfusion":    { say: "trans-FYOO-zhun", def: "Giving a patient blood donated by someone else — common for tiny preemies." },
  "murmur":         { say: "MUR-mer", def: "A whooshing sound in the heartbeat heard through a stethoscope — often blood rushing through an open ductus." },

  // --- physics ---
  "wavelength":     { say: "WAYV-length", def: "The spacing between a light wave's ripples. Long waves are red; short waves are violet." },
  "spectrum":       { say: "SPEK-trum", def: "The rainbow of colors that white light spreads into — plus the invisible ends." },
  "infrared":       { say: "in-fruh-RED", def: "Invisible light with longer waves than red. You feel it as warmth; the pulse ox uses it." },
  "ultraviolet":    { say: "ul-truh-VY-uh-lit", def: "Invisible light with shorter waves than violet. The sunburn part of sunlight." },
  "absorb":         { say: "ub-ZORB", def: "To soak up light. A thing's color is the light it does NOT absorb." },
  "absorbs":        { say: "ub-ZORBZ", def: "Soaks up light. A tomato absorbs blue and green and bounces back red." },
  "prism":          { say: "PRIZ-um", def: "A wedge of glass that bends each color differently and spreads white light into a rainbow." },
  "phototherapy":   { say: "foe-toe-THAIR-uh-pee", def: "Treating with light. The bili light is phototherapy for jaundice." },
  "retina":         { say: "RET-ih-nuh", def: "The light-sensing layer at the back of the eye. In preemies it's still growing." },
  "pulse oximetry": { say: "pulse ok-SIM-eh-tree", def: "Measuring blood oxygen with red and infrared light through the skin, invented by Takuo Aoyagi in the 1970s." },

  // --- calculus ---
  "total":          { say: "TOE-tul", def: "How much has piled up. Rate × time — calculus's second big question." },
  "area under the curve": { say: "AIR-ee-uh under the kurv", def: "The shaded region beneath a rate line. It equals the total that piled up." },
  "bolus":          { say: "BOW-lus", def: "One measured meal given at once — a 20 mL feed every 3 hours — rather than a continuous drip." },
  "integral":       { say: "IN-tuh-grul", def: "The calculus word for the exact area under a curve, found by slicing. Its symbol is ∫, a stretched S for 'sum'." },
  "polygon":        { say: "POL-ee-gon", def: "A flat shape with straight sides. Archimedes squeezed a circle between polygons with 96 sides." },
  "intake":         { say: "IN-take", def: "Everything that goes into a patient — feeds, IV fluids, TPN — added up on the I&O sheet." },
  "output":         { say: "OUT-put", def: "Everything that comes out — mostly urine, measured by weighing diapers. 1 gram = 1 mL." },
  "slice":          { say: "slyss", def: "To cut time into thin strips so each one can be treated as a rectangle. The heart of finding a total." },

  // --- statistics ---
  "the median":     { say: "the MEE-dee-un", def: "The middle value after lining numbers up in order. One wild number can't drag it around." },
  "median":         { say: "MEE-dee-un", def: "The middle value after lining numbers up. Half are below, half above." },
  "outlier":        { say: "OUT-ly-er", def: "A value far from the rest — the 1,600-gram baby in a room of 900s. It drags the mean but not the median." },
  "percentile":     { say: "per-SEN-tile", def: "Your place in line, out of 100. The 10th percentile has 10 of every 100 at or below it. A position, not a grade." },
  "percentiles":    { say: "per-SEN-tilez", def: "Places in line, out of 100. The 50th is the median." },
  "growth chart":   { say: "grohth chart", def: "Percentile curves by age, so one baby's dots can be read against many babies." },
  "gestational age": { say: "jess-TAY-shun-ul ayj", def: "How many weeks a baby has been growing since conception. Full term is about 40; preemie charts use it along the bottom." },
  "small for gestational age": { say: "small for jess-TAY-shun-ul ayj", def: "Below the 10th percentile for the week you were born. A flag to look for a reason, not a diagnosis." },
  "falling off the curve": { say: "FALL-ing off the kurv", def: "Crossing percentile lines downward over time — the growth alarm doctors watch for." },

  // --- genetics ---
  "enzyme":         { say: "EN-zime", def: "A protein whose job is a chemical task — snipping, gluing, taking a molecule apart. Thousands of kinds; one clears bilirubin." },
  "enzymes":        { say: "EN-zimez", def: "Proteins that do chemical jobs. A typo in an enzyme's recipe means its job doesn't get done." },
  "phenylalanine":  { say: "fen-il-AL-uh-neen", def: "One of the twenty protein building blocks, found in milk, meat, and eggs. It piles up in PKU." },
  "PKU":            { say: "P K U", def: "Phenylketonuria: a broken enzyme lets phenylalanine pile up and harm the brain. Caught by the heel prick; prevented by a special diet." },
  "newborn screening": { say: "NOO-born SKREE-ning", def: "Testing every baby for hidden, treatable conditions: the heel-prick card, the hearing test, and the pulse-ox heart check." },
  "screening test": { say: "SKREE-ning test", def: "A wide net for catching a disease early. A positive means 'test again, properly, now' — not a diagnosis." },
  "heel prick":     { say: "heel prik", def: "The tiny poke on the side of a newborn's heel that gives the drops of blood for the screening card." },
  "hypothyroidism": { say: "hy-po-THY-royd-iz-um", def: "Too little thyroid hormone — the most common condition the heel prick catches. Fixed with one small pill a day." },
  "thyroid":        { say: "THY-royd", def: "A gland in the neck that makes a hormone the body needs for growth and brain development." },
  "amino acid":     { say: "uh-MEE-no ASS-id", def: "A protein building block. There are twenty kinds; phenylalanine is one." },

  // --- psychology ---
  "attachment":     { say: "uh-TATCH-ment", def: "The built-in bond that makes a baby seek closeness to a caregiver and explore from that safe base." },
  "secure base":    { say: "sih-KYOOR bayss", def: "The caregiver a baby checks back with and returns to. Mary Ainsworth's phrase." },
  "secure":         { say: "sih-KYOOR", def: "Ainsworth's word for a strong rope: upset when the caregiver leaves, comforted fast when they return, then back to play." },
  "strange situation": { say: "straynj sit-yoo-AY-shun", def: "Ainsworth's twenty-minute experiment: mother leaves, stranger stays, mother returns — what does the baby do?" },
  "still face":     { say: "still fayss", def: "Tronick's two-minute experiment: the caregiver goes blank, and the baby works to restart the game." },
  "serve and return": { say: "serv and rih-TURN", def: "The back-and-forth between baby and caregiver — a smile answered, a sound copied — thousands of times a day." },
  "responsive":     { say: "rih-SPON-siv", def: "Answering a baby's signals reliably. Not perfectly — reliably. It's what builds a secure rope." },
  "bonding":        { say: "BON-ding", def: "The rope forming between a baby and its parents. In a NICU it's a treatment, not just niceness." },

  // --- sociology ---
  "rates":          { say: "raytz", def: "Counts divided by the size of the group — per 100 or per 1,000 — so different groups can be compared." },
  "infant mortality": { say: "IN-funt mor-TAL-ih-tee", def: "Babies who die before their first birthday, usually given per 1,000 births." },
  "disparity":      { say: "diss-PAIR-ih-tee", def: "A gap between groups that shouldn't be there — in care, in survival, in health." },
  "disparities":    { say: "diss-PAIR-ih-teez", def: "Gaps between groups in care or health that shouldn't exist." },
  "social determinants of health": { say: "SO-shul dih-TER-mih-nunts of helth", def: "The conditions of life — money, housing, food, stress, distance, respect — that shape who gets sick and who gets care." },
  "maternity care desert": { say: "muh-TER-nih-tee care DEZ-ert", def: "A county with no hospital or clinic that delivers babies. More than two million American women live in one." },
  "public health":  { say: "PUB-lik helth", def: "Caring for the health of whole groups and places, not one patient at a time." },
  "fieldwork":      { say: "FEELD-werk", def: "Going and looking: the sociologist's way of collecting data." },
  "preterm":        { say: "PREE-term", def: "Born before 37 weeks. About one baby in ten worldwide — around 13 million a year." }
};
