/* NICUniversity vocabulary. Any of these words appearing in lesson text becomes tappable.
   say: how to pronounce it (also used by read-aloud). def: plain-language definition. */
window.VOCAB = {
  // --- university words ---
  "lecture":        { say: "LEK-chur", def: "A class where the professor teaches and you listen, think, and take notes." },
  "recitation":     { say: "reh-sih-TAY-shun", def: "A smaller session for practicing what the lecture taught — at NICUniversity, it's where you do your homework." },
  "professor":      { say: "pruh-FESS-er", def: "A teacher at a university. Most professors also do research — they discover new things, not just teach old ones." },
  "syllabus":       { say: "SILL-uh-bus", def: "The plan for a course: what you'll learn each week and how you'll be graded." },
  "transcript":     { say: "TRAN-script", def: "The official record of the courses you've taken and how you did." },
  "seminar":        { say: "SEM-ih-nar", def: "A small class built around discussion instead of a lecture." },
  "undergraduate":  { say: "un-der-GRAD-yoo-it", def: "A university student earning a first degree — usually four years. Doctors go to medical school after that." },
  "pre-med":        { say: "pree-MED", def: "Short for 'pre-medical' — the courses you take in university to prepare for medical school." },
  "neonatologist":  { say: "nee-oh-nay-TOL-uh-jist", def: "A doctor who specializes in newborn babies, especially sick and premature ones." },
  "premature":      { say: "pree-muh-CHOOR", def: "Born early — before 37 weeks of pregnancy. A premature baby is a 'preemie'." },

  // --- chemistry ---
  "atom":           { say: "AT-um", def: "The tiniest building block of ordinary matter. Everything you can touch is made of atoms — and they're so small that a single drop of water holds more of them than there are stars in the galaxy." },
  "atoms":          { say: "AT-umz", def: "The tiniest building blocks of ordinary matter. Everything you can touch is made of atoms." },
  "molecule":       { say: "MOL-uh-kyool", def: "Two or more atoms joined together. Water, oxygen gas, and sugar are all molecules." },
  "molecules":      { say: "MOL-uh-kyoolz", def: "Groups of atoms joined together. Water, oxygen gas, and sugar are all molecules." },
  "element":        { say: "EL-uh-ment", def: "One kind of atom. Oxygen, carbon, hydrogen, and gold are elements. There are about 118 of them, and only a few dozen matter for living things." },
  "elements":       { say: "EL-uh-ments", def: "The different kinds of atoms. Oxygen, carbon, hydrogen, and gold are elements." },
  "chemical formula": { say: "KEM-ih-kul FOR-myoo-luh", def: "The short recipe for a molecule, like H₂O — it lists which atoms and how many of each." },
  "subscript":      { say: "SUB-script", def: "A small number written low and to the right, like the 2 in H₂O. It tells you how many of that atom are in the molecule." },
  "oxygen":         { say: "OK-sih-jin", def: "The gas your cells need to burn fuel for energy. About one-fifth of the air is oxygen." },
  "carbon dioxide": { say: "KAR-bun dy-OK-side", def: "The waste gas your cells make when they burn fuel — CO₂. You breathe it out; plants breathe it in." },
  "nitrogen":       { say: "NY-truh-jin", def: "The gas that makes up most of the air (about 78%). You breathe it in and right back out — your body mostly ignores it." },
  "gas exchange":   { say: "gas eks-CHAYNJ", def: "The swap in the lungs: oxygen moves from air into blood, and carbon dioxide moves from blood into air." },
  "alveoli":        { say: "al-VEE-oh-lye", def: "The hundreds of millions of microscopic air balloons in the lungs where gas exchange happens." },
  "hemoglobin":     { say: "HEE-muh-glow-bin", def: "The protein inside red blood cells that grabs oxygen and carries it around the body. It's what makes blood red." },
  "surfactant":     { say: "sur-FAK-tunt", def: "The soap-like liquid that coats the lungs' air balloons so they don't stick shut. Preemies don't make enough of it yet." },
  "acid":           { say: "ASS-id", def: "A chemical that tastes sour and can be corrosive — lemon juice and stomach juice are acids. Blood is supposed to be only very slightly on the opposite (base) side." },
  "chemist":        { say: "KEM-ist", def: "A scientist who studies what things are made of and how they change." },
  "chemistry":      { say: "KEM-iss-tree", def: "The science of what things are made of and how they change into other things." },
  "experiment":     { say: "ek-SPEHR-ih-ment", def: "A careful test to find out if an idea is true. Scientists change one thing and watch what happens." },
  "percent":        { say: "per-SENT", def: "Out of one hundred. 21 percent means 21 out of every 100." },

  // --- biology ---
  "cell":           { say: "sell", def: "The smallest living unit of a body — a tiny bag of chemistry with its own instruction book. You are made of trillions of them." },
  "cells":          { say: "sells", def: "The smallest living units of a body. You are made of trillions of them, and you started as exactly one." },
  "nucleus":        { say: "NOO-klee-us", def: "The control center of a cell, where the DNA instruction book is kept." },
  "membrane":       { say: "MEM-brayn", def: "The thin skin around a cell that decides what comes in and what goes out." },
  "mitochondria":   { say: "my-toh-KON-dree-uh", def: "The power plants of the cell. They burn sugar with oxygen to make energy — that's where the oxygen you breathe finally gets used." },
  "cytoplasm":      { say: "SY-toh-plaz-um", def: "The jelly-like liquid that fills a cell and holds its parts." },
  "tissue":         { say: "TISH-oo", def: "A group of similar cells working together — muscle tissue, skin tissue, nerve tissue." },
  "tissues":        { say: "TISH-ooz", def: "Groups of similar cells working together — muscle, skin, nerve, and so on." },
  "organ":          { say: "OR-gun", def: "A body part made of several tissues doing one job — the heart, lungs, brain, and skin are all organs." },
  "organs":         { say: "OR-gunz", def: "Body parts made of several tissues doing one big job — the heart, lungs, brain, and skin." },
  "microscope":     { say: "MY-kruh-skope", def: "A tool with lenses that makes tiny things look big enough to see." },
  "microscopic":    { say: "my-kruh-SKOP-ik", def: "Too small to see without a microscope." },
  "cell division":  { say: "sell dih-VIZH-un", def: "When one cell splits into two. It's how bodies grow and heal — and how one cell becomes a whole baby." },
  "bacteria":       { say: "bak-TEER-ee-uh", def: "Tiny one-celled living things. Most are harmless or helpful; some cause infections." },
  "red blood cell": { say: "red blud sell", def: "The disc-shaped cell that carries oxygen using hemoglobin. Unusual: it has no nucleus, leaving more room for cargo." },
  "biologist":      { say: "by-OL-uh-jist", def: "A scientist who studies living things." },
  "biology":        { say: "by-OL-uh-jee", def: "The science of living things — how they're built, how they work, how they grow." },
  "trillion":       { say: "TRILL-yun", def: "A thousand billion — 1,000,000,000,000. Your body has around 30 trillion cells." },
  "organism":       { say: "OR-guh-niz-um", def: "Any single living thing — a bacterium, a tree, a baby, you." },
  "bilirubin":      { say: "bill-ee-ROO-bin", def: "The yellow leftover from recycling worn-out red blood cells. Too much of it causes jaundice." },

  // --- physics ---
  "pressure":       { say: "PRESH-er", def: "A push spread over an area. The same push on a smaller area makes a bigger pressure." },
  "area":           { say: "AIR-ee-uh", def: "How much surface something covers — the size of the flat space a push lands on." },
  "atmosphere":     { say: "AT-muss-feer", def: "The blanket of air around the Earth. Its weight presses on everything — about 760 mmHg at sea level." },
  "barometer":      { say: "buh-ROM-eh-ter", def: "An instrument that measures air pressure. Torricelli's mercury tube was the first one." },
  "mercury":        { say: "MER-kyoo-ree", def: "A silvery metal that is liquid at room temperature and about 13.6 times heavier than water. Old blood pressure meters used a column of it." },
  "mmHg":           { say: "millimeters of mercury", def: "A unit of pressure: how many millimeters high the push could lift a column of mercury. Used for blood pressure." },
  "cmH₂O":          { say: "centimeters of water", def: "A unit of gentle pressure: how many centimeters high the push could lift a column of water. Used for CPAP and ventilators." },
  "physicist":      { say: "FIZZ-ih-sist", def: "A scientist who studies forces, energy, motion, light, sound, and heat — the rules everything follows." },
  "physics":        { say: "FIZZ-iks", def: "The science of forces, energy, and motion — the rules that everything, living or not, has to follow." },
  "air leak":       { say: "air leek", def: "When an over-stretched air sac in the lung pops and air escapes into the chest, squashing the lung. A known danger of too much pressure." },
  "ventilator":     { say: "VEN-tih-lay-ter", def: "The machine that breathes for a baby through a tube in the windpipe, with every puff's size and pressure set precisely." },

  // --- calculus ---
  "calculus":       { say: "KAL-kyoo-lus", def: "The mathematics of change: how fast something is changing, and how much it adds up to over time." },
  "rate":           { say: "rayt", def: "How much something changes in each unit of time — like grams per day or miles per hour." },
  "rate of change": { say: "rayt of chaynj", def: "How much something changes per unit of time. Change ÷ time." },
  "slope":          { say: "slohp", def: "How steep a line on a graph is. On a weight graph, the slope IS the rate of growth." },
  "graph":          { say: "graf", def: "A picture of numbers. A line graph shows how something changes over time." },
  "average":        { say: "AV-er-ij", def: "The typical amount, found by adding everything up and dividing by how many there are." },
  "negative":       { say: "NEG-uh-tiv", def: "Less than zero. A negative rate of change means something is going down — like a newborn's weight in the first days." },
  "velocity":       { say: "veh-LOSS-ih-tee", def: "Speed with a direction. Doctors call the rate of growth on a growth chart 'growth velocity'." },
  "derivative":     { say: "deh-RIV-uh-tiv", def: "The calculus word for the rate of change at one exact moment — the steepness of the curve right there." },
  "kilogram":       { say: "KILL-oh-gram", def: "1,000 grams — about the weight of a liter of water. A 1 kg baby is a very small preemie." },
  "trend":          { say: "trend", def: "The overall direction of many measurements over time — up, down, or flat — as opposed to one single reading." },

  // --- statistics ---
  "statistics":     { say: "stuh-TISS-tiks", def: "The science of making sense of many numbers — what's typical, what's unusual, and how sure we can be." },
  "the mean":       { say: "the meen", def: "The average: add all the numbers, then divide by how many there are." },
  "the range":      { say: "the raynj", def: "The biggest number minus the smallest — how spread out the numbers are." },
  "data":          { say: "DAY-tuh", def: "Measurements and facts collected to learn something. One heart rate is a number; a hundred of them is data." },
  "Apgar score":    { say: "AP-gar score", def: "A 0-to-10 score of how a newborn is doing at 1 and 5 minutes after birth: heart rate, breathing, muscle tone, reflexes, and color, each scored 0, 1, or 2." },
  "anesthesiologist": { say: "an-ess-thee-zee-OL-uh-jist", def: "A doctor who keeps patients safely asleep and pain-free during operations — and watches their breathing and heart the whole time." },
  "normal range":   { say: "NOR-mul raynj", def: "The zone where most healthy people's measurements fall, found by measuring thousands of them." },

  // --- genetics ---
  "genetics":       { say: "jeh-NET-iks", def: "The science of the instruction book inside cells — DNA, genes, and how traits pass from parents to children." },
  "DNA":            { say: "D N A", def: "The long molecule that stores the body's instructions, written in four chemical letters: A, T, C, G." },
  "gene":           { say: "jeen", def: "One recipe in the DNA instruction book — the instructions for building one protein." },
  "genes":          { say: "jeenz", def: "The recipes in the DNA instruction book. Humans have about 20,000." },
  "chromosome":     { say: "KROH-muh-sohm", def: "One volume of the instruction book — a long, tightly wound piece of DNA. Human body cells have 46, in 23 pairs." },
  "chromosomes":    { say: "KROH-muh-sohmz", def: "The volumes of the instruction book. Human body cells have 46, in 23 pairs — one of each pair from each parent." },
  "protein":        { say: "PROH-teen", def: "A working molecule built from a gene's recipe. Hemoglobin, surfactant, and muscle are all made of proteins." },
  "proteins":       { say: "PROH-teenz", def: "The working molecules of the body, each built from a gene's recipe." },
  "identical twins":{ say: "eye-DEN-tih-kul twinz", def: "Twins from one fertilized egg that split in two — they share the same DNA." },
  "fraternal twins":{ say: "fruh-TER-nul twinz", def: "Twins from two separate eggs — ordinary siblings who happened to share a womb." },
  "mutation":       { say: "myoo-TAY-shun", def: "A typo in the DNA code. Most are harmless; a few cause diseases like sickle cell." },
  "double helix":   { say: "DUB-ul HEE-liks", def: "The twisted-ladder shape of the DNA molecule." },
  "inherit":        { say: "in-HAIR-it", def: "To receive from your parents — features passed down through DNA." },

  // --- psychology ---
  "psychology":     { say: "sy-KOL-uh-jee", def: "The science of the mind and behavior — what people (and babies) think, feel, and do." },
  "psychologist":   { say: "sy-KOL-uh-jist", def: "A scientist who studies minds and behavior." },
  "behavior":       { say: "bee-HAY-vyer", def: "What someone does — looking, sucking, turning, crying, smiling. Babies can't talk, so behavior is how they tell us things." },
  "neurons":        { say: "NOOR-onz", def: "Brain cells that send signals to each other. You have about 86 billion, wiring up at over a million connections a second in early life." },
  "neuron":         { say: "NOOR-on", def: "A brain cell that sends signals. A newborn's neurons are connecting at more than a million connections per second." },
  "developmental care": { say: "dih-vel-up-MEN-tul care", def: "Running a NICU around the baby's needs — dim lights, less noise, protected sleep, gentle handling, parents close." },
  "stress":         { say: "stress", def: "The body's alarm state: faster heart, stress hormones, tense muscles. Babies have it too — and it can be measured." },
  "womb":           { say: "woom", def: "The uterus — the place inside the mother where a baby grows before birth." },
  "third trimester": { say: "third try-MESS-ter", def: "The last three months of pregnancy (about weeks 27–40), when the brain and lungs do most of their finishing work." },

  // --- sociology ---
  "sociology":      { say: "so-see-OL-uh-jee", def: "The science of people in groups — how they organize, the roles they take, and the rules they follow." },
  "sociologist":    { say: "so-see-OL-uh-jist", def: "A scientist who studies groups, organizations, and societies." },
  "society":        { say: "suh-SY-eh-tee", def: "A large group of people living and working together with shared rules and roles. A hospital is a small society." },
  "role":           { say: "rohl", def: "The job and expected behavior a person has in a group — nurse, parent, student, captain." },
  "hierarchy":      { say: "HY-er-ar-kee", def: "A ranking of who is in charge of whom. Useful for decisions; dangerous when it stops people from speaking up." },
  "regionalization": { say: "ree-jun-ul-ih-ZAY-shun", def: "Organizing hospitals so the sickest babies are born in, or moved to, the ones equipped to care for them." },
  "respiratory therapist": { say: "RESS-pir-uh-tor-ee THAIR-uh-pist", def: "The breathing-machine expert on the team — runs ventilators and CPAP and helps at every fragile delivery." },
  "pharmacist":     { say: "FAR-muh-sist", def: "The medicine expert — prepares TPN recipes and checks every dose for tiny bodies." },
  "social worker":  { say: "SO-shul WER-ker", def: "The team member who supports families — stress, money, housing, paperwork, and getting through the hardest days." },
  "lactation consultant": { say: "lak-TAY-shun kun-SUL-tunt", def: "An expert who helps mothers pump and provide breast milk for their babies." },
  "infection control": { say: "in-FEK-shun kun-TROHL", def: "Everything done to keep germs away from patients — handwashing, cleaning, gloves, gowns." },

  // --- shared NICU words (flashbacks) ---
  "isolette":       { say: "EYE-so-let", def: "The clear, warm, humid incubator bed that keeps a preemie at the right temperature." },
  "pulse oximeter": { say: "pulse ok-SIM-eh-ter", def: "The glowing foot band that measures oxygen in the blood using red and infrared light." },
  "CPAP":           { say: "SEE-pap", def: "Continuous Positive Airway Pressure — a gentle air cushion through nose prongs that keeps a preemie's lungs partly inflated." },
  "jaundice":       { say: "JAWN-diss", def: "Yellow-tinted skin from bilirubin building up. Very common in newborns; treated with blue light." },
  "kangaroo care":  { say: "kang-guh-ROO care", def: "Holding a baby skin-to-skin on a parent's chest. It keeps the baby warm and steadies heart rate and breathing." }
};
